# Generated by Django 4.0.2 on 2022-02-03 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_battle", models.BooleanField(default=True)),
                ("can_battle_in_own", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=150)),
                (
                    "claim_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_auth.claims",
                    ),
                ),
            ],
        ),
    ]
