# Generated by Django 4.0.2 on 2022-02-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_claims_rename_user_users_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_auth.roles'),
        ),
    ]
