# Generated by Django 4.0.3 on 2022-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_users_role_id'),
        ('cage', '0002_question_cages_question_creator_question_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='custom_auth.users'),
        ),
    ]
